### PR TITLE
Add output_text_description_file input

### PR DESCRIPTION
**Pull request by benreynolds-drizly**
The text property of the github check output object supports markdown but it is currently prohibitively difficult to provide meaningful markdown embedded in the inline JSON within the workflow yaml. This addition allows previous steps to generate markdown files which can then be provided to this action.

Example usage:
```yaml
      - uses: benreynolds-drizly/checks-action@add-output-text-description-file
        id: update-check
        with:
          check_id: ${{ steps.create-check.outputs.check_id }}
          token: ${{ steps.fetch-token.outputs.token }}
          repo: ${{ github.event.client_payload.GITHUB_REPOSITORY }}
          sha: ${{ github.event.client_payload.GITHUB_SHA }}
          output: |
            {
              "summary": "This is my summary"
            }
          output_text_description_file: ${{ steps.example.outputs.report-path }}
          conclusion: ${{ job.status }}
```

Example of the type of the report that can be generated using this approach:

Screen Shot 2021-07-21 at 1 51 13 PM

### CODE REVIEW

**Comment by LouisBrunner** [comment]
Looks good to me! What's the reason of requiring both `output` and `output_text_description_file`?

**Comment by benreynolds-drizly** [comment]
`summary` is required when providing an output and rather than adding a second new input (something like `output_summary`) I figured it would be cleanest to just have `output_text_description_file` as an optional override.

**Comment by LouisBrunner** [comment]
Oh right, my bad, I forgot `output` was a JSON object 🤦

**Comment by atDTSystemsLtd** [comment]
Any idea when this will be released? `output_text_description_file` is extremely useful feature.

**Comment by LouisBrunner** [comment]
@atDTSystemsLtd Just released it as `1.2.0`

**Pull request merged**
